defmodule SkillSanity.Repo.Migrations.UseCiStrings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:skills) do
      modify :name, :citext
      modify :slug, :citext
    end

    alter table(:skill_variations) do
      modify :variation, :citext
    end
  end

  def down do
    alter table(:skill_variations) do
      modify :variation, :text
    end

    alter table(:skills) do
      modify :slug, :text
      modify :name, :text
    end
  end
end
