defmodule SkillSanity.Repo.Migrations.AddSourceAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:skills) do
      add :source, :citext, null: false, default: "seed"
    end

    alter table(:skills) do
      modify :source, :citext, null: false, default: nil
    end

    alter table(:skill_variations) do
      add :source, :citext, null: false, default: "seed"
    end

    alter table(:skill_variations) do
      modify :source, :citext, null: false, default: nil
    end
  end

  def down do
    alter table(:skill_variations) do
      remove :source
    end

    alter table(:skills) do
      remove :source
    end
  end
end
