defmodule SkillSanity.Repo.Migrations.AddSearchLogResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:search_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :search_term, :text, null: false
      add :confidence, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :matched_skill_id,
          references(:skills,
            column: :id,
            name: "search_logs_matched_skill_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :matched_variation_id,
          references(:skill_variations,
            column: :id,
            name: "search_logs_matched_variation_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:search_logs, "search_logs_matched_skill_id_fkey")

    drop constraint(:search_logs, "search_logs_matched_variation_id_fkey")

    drop table(:search_logs)
  end
end
