name: Deploy Staging

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy-staging:
    name: Deploy app
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    concurrency: deploy-staging-group
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Create .env file
        run: cp .env.example .env
      - name: Output app revision
        run: make get-revision
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.3.24 # renovate: datasource=github-releases depName=flyctl packageName=superfly/flyctl versioning=semver
      - run: flyctl deploy --config fly.staging.toml -e APP_REVISION="$(make get-revision)"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
