name: Release

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      pull-requests: read

  test-docker-build:
    uses: ./.github/workflows/test-docker-build.yml
    permissions:
      contents: read
      pull-requests: read

  release:
    needs:
      - test
      - test-docker-build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false

      - name: Set up Elixir
        id: setup-beam
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        with:
          version-type: strict
          version-file: .tool-versions

      - name: Restore dependencies cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        env:
          cache-key: deps
        with:
          key: ${{ env.cache-key }}-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}-git-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-key }}-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}-
            ${{ env.cache-key }}-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-
          path: |
            deps
            _build

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix do deps.get, deps.compile

      - name: Run Semantic Release
        run: mix semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
