name: Test Docker Build

on:
  push:
    # ignore branches where the release workflow runs as it already calls this one
    branches-ignore:
      - main
      - dev
    # run only when the Dockerfile changes
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  # ignore the push event trigger if a PR is open for the current branch
  prevent_duplicate_checks:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - uses: insurgent-lab/is-in-pr-action@129df59687402c4a9c81a9a9e88d7448cdbba541 # v0.2.0
        id: isInPR
    outputs:
      should-run: ${{ !(steps.isInPR.outputs.result == 'true' && github.event_name == 'push') }}

  test-docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest

    needs: prevent_duplicate_checks
    if: ${{ needs.prevent_duplicate_checks.outputs.should-run == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Verify base image existence
        run: docker build --target base .
